name: test Python with Docker

# This workflow is triggered on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Define the job
  build:
    runs-on: ubuntu-latest  # Specify the operating system

    steps:
    # Step 1: Checkout the repository code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Python (version 3.11 as an example)
    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    # Step 3: Install dependencies from requirements.txt 
    - name: Install dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install -r requirements.txt
        fi

    # Step 4: Run tests
    - name: Run tests
      run: |
        if [ -f tests/test_sample.py ]; then
          pytest tests/test_sample.py  # Adjust the test file location and command
        fi

    # Step 5: Build the Docker image (assuming a Dockerfile exists in the repo)
    - name: Build Docker image
      run: |
        docker build -t test-python-app

    # Step 6: Run Docker container (optional)
    - name: Run Docker container
      run: |
        docker run -d -p 5000:8000 --name test-python-container test-python-app

